### ISSUE TITLE
Building GUI sprays files into CLI submodule

### ISSUE THREAD

**Issue by iedemam** [letheanVPN/lethean-gui#45]
Annoying bit of cleanup needed here...

````
$ git status
	modified:   intense (modified content, untracked content)
$ cd intense
$ git status
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    include/INode.h
	deleted:    include/IWallet.h

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	version.sh
````

**Comment by mtl1979** [comment]
Shouldn't "version.sh" just be added to .gitignore if the build files are created directly to sourced tree... Preferred way is to create all files under build/ directory... as far as I understand version.sh needs to know the absolute path to the source tree to determine the version stamp, but it could be passed to it as a parameter too...

**Comment by pallas1** [comment]
looks like it does it on purpose everytime:

echo "GUI_MONERO_VERSION=\"$VERSIONTAG\"" > $MONERO_DIR/version.sh

maybe just .gitignore is the best solution.

Don't know about the other two files, they are tracked by git, but shouldn't.

**Comment by mtl1979** [comment]
I think it did create version.sh in the source tree because the original version of get_libwallet_api.sh did delete the build tree, so it would have also deleted the generated version.sh and that would have caused unnecessary rebuild of libwallet everytime even if it was not changed. version.sh loads utils.sh from source tree, but already uses variable magic to determine where it is located.
