### ISSUE TITLE
 Wallet (2.0.2.1, mac) freeze and don t respond, after big transactions.

### ISSUE THREAD

**Issue by tonyxia2016** [letheanVPN/lethean-gui#58]
Also, wallet (2.0.2.1, mac) freeze and don t respond, after big transactions.
I send to exchange 6 transactions (3 of them was like 90 000 itns) and wallet freeze 3 times; forced to restart wallet.

Hope you fix it in the next updates.

Note: copied from https://bitcointalk.org/index.php?topic=2090765.new#new

**Comment by valiant1x** [comment]
This issue is probably related to the large transactions comprising many small inputs. If all of your wallet outputs were small transactions (from mining for example), it takes time to assemble them into a single tx. The wallet has to work to put them all together in one transaction, which takes CPU power. This is due to the nature of RingCT transactions.

Possible solutions, ordered by increasing complexity:
1. De-couple the wallet/bc scanning to a separate thread so the UI doesn't freeze, and display a 'loading'/progress indicator in the UI when this is occurring.
2. Assess the wallet input scanning code for possible optimization
